# Generated by Django 4.2 on 2025-07-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='difficulties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='difficulties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
